### ISSUE TITLE
[$30] - 'Reminder' option is not saved after user turned on it

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-kidney-android#67]
## Steps to Reproduce

1. Login as a valid user
2. Complete the profile data and click Generate Goals
3. Go to Home page
4. Click 'Goal' > Workout
5. Select the Reminder > Save my Goal
6. Click 'Workout' again and check

## Actual Result(s)

- 'Reminder' option is not saved after user turned on it

## Expected Result(s)

- Must stay ON once it is save

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

## Image(s)/Video(s)/Console Log/Crash Log

![screenshot_2018-08-29-15-59-57](https://user-images.githubusercontent.com/4592712/44815346-e3d25a00-aba4-11e8-8224-d35c82270813.png)

**Comment by talesforce** [comment]
@gatorboy - Looks like this one still has merge conflicts

**Comment by gatorboy** [comment]
Resolved the conflicts here. https://github.com/topcoderinc/va-kidney-android/pull/139
