### ISSUE TITLE
App crash when user enters period (.) to the 'Amount' field and tap 'Add Meal'

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-kidney-android#82]
## Steps to Reproduce

1. Login as a valid user
2. Complete the profile data and click Generate Goals
3. Go to Home page
4. Tap Menu > Food/Drug
5. Tap on a meal (if not creare a new meal)
6. Tap 'Add Meal'
7. Type 'Bea' into the 'Meal or Liquid Item' field and select the first one
8. Set Amount as . (.) Period
9. Set the Unit as oz (mass)
10. Tap 'Add Meal'
11. Check the item amount

## Actual Result(s)

- App crash when user enters period (.) to the 'Amount' field and tap 'Add Meal'

## Expected Result(s)

- Must not crash the app
- iPhone App (Comparison) Because this is the same app all the options and wording must be same

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

## Image(s)/Video(s)/Console Log/Crash Log

```
08-30 12:42:26.482: D/AndroidRuntime(12630): Shutting down VM
08-30 12:42:26.482: E/AndroidRuntime(12630): FATAL EXCEPTION: main
08-30 12:42:26.482: E/AndroidRuntime(12630): Process: com.topcoder.vakidney, PID: 12630
08-30 12:42:26.482: E/AndroidRuntime(12630): java.lang.NumberFormatException: Invalid double: ""
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at java.lang.StringToReal.initialParse(StringToReal.java:176)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at java.lang.StringToReal.parseDouble(StringToReal.java:282)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at java.lang.Double.parseDouble(Double.java:301)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at com.topcoder.vakidney.popup.AddMealDrugPopup$1.onClick(AddMealDrugPopup.java:149)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.view.View.performClick(View.java:5697)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.widget.TextView.performClick(TextView.java:10826)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.view.View$PerformClick.run(View.java:22526)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.os.Handler.handleCallback(Handler.java:739)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.os.Looper.loop(Looper.java:158)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at java.lang.reflect.Method.invoke(Native Method)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-30 12:42:26.482: E/AndroidRuntime(12630): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

[23. Log.txt](https://github.com/topcoderinc/va-kidney-android/files/2337296/23.Log.txt)

**Comment by talesforce** [comment]
@sdgun - Thanks for the clarification. 

Since this was already fixed by a previous PR, no prize will be paid out for this.
