### ISSUE TITLE
'Recommendations' tab title is wrong

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-kidney-android#89]
## Steps to Reproduce

1. Login as a valid user
2. Complete the profile data and click Generate Goals
3. Go to Home page
4. Tap Menu > Recommendations
5. Check the title

## Actual Result(s)

- 'Recommendations'

## Expected Result(s)

- 'Nutrition and Drug Interaction'
- iPhone App (Comparison) Because this is the same app all the options and wording must be same

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

## Image(s)/Video(s)/Console Log/Crash Log

![device-2018-08-30-194427 - copy](https://user-images.githubusercontent.com/4592712/44887154-4bb19f00-ac90-11e8-85cc-f706afb8c67f.png)

**Comment by talesforce** [comment]
@Manoj85 - Please provide an update on this issue

**Comment by talesforce** [comment]
@sdgun - I don't think this is a show stopper, I'm closing this one out
